---
kind: Service
apiVersion: v1
metadata:
  name: cosmos-reason-service
  namespace: runai-embodied-ai
spec:
  ports:
    - name: console
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
  selector:
    app: jupyterlab-0

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: cosmos-reason-service
  namespace: runai-embodied-ai
spec:
  host: embodied-ai-cosmos-reason.apps.octocp.alexnet.htx
  to:
    kind: Service
    name: cosmos-reason-service
    weight: 100
  port:
    targetPort: console
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None